In [ ]:
import numpy as np
import tensorflow as tf

x=[]
y=[]
for i in range(10000):
  temp = []
  for j in range(i,i+4):
    temp.append(([j/10]))
  x.append(temp)
  y.append((i+4)/10)

print(x, y)

X = np.array(x)
Y = np.array(y)

for i in range(len(X)):
  print(X[i], Y[i])

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[[875. ]
 [875.1]
 [875.2]
 [875.3]] 875.4
[[875.1]
 [875.2]
 [875.3]
 [875.4]] 875.5
[[875.2]
 [875.3]
 [875.4]
 [875.5]] 875.6
[[875.3]
 [875.4]
 [875.5]
 [875.6]] 875.7
[[875.4]
 [875.5]
 [875.6]
 [875.7]] 875.8
[[875.5]
 [875.6]
 [875.7]
 [875.8]] 875.9
[[875.6]
 [875.7]
 [875.8]
 [875.9]] 876.0
[[875.7]
 [875.8]
 [875.9]
 [876. ]] 876.1
[[875.8]
 [875.9]
 [876. ]
 [876.1]] 876.2
[[875.9]
 [876. ]
 [876.1]
 [876.2]] 876.3
[[876. ]
 [876.1]
 [876.2]
 [876.3]] 876.4
[[876.1]
 [876.2]
 [876.3]
 [876.4]] 876.5
[[876.2]
 [876.3]
 [876.4]
 [876.5]] 876.6
[[876.3]
 [876.4]
 [876.5]
 [876.6]] 876.7
[[876.4]
 [876.5]
 [876.6]
 [876.7]] 876.8
[[876.5]
 [876.6]
 [876.7]
 [876.8]] 876.9
[[876.6]
 [876.7]
 [876.8]
 [876.9]] 877.0
[[876.7]
 [876.8]
 [876.9]
 [877. ]] 877.1
[[876.8]
 [876.9]
 [877. ]
 [877.1]] 877.2
[[876.9]
 [877. ]
 [877.1]
 [877.2]] 877.3
[[877. ]
 [877.1]
 [877.2]
 [877.3]] 877.4
[[877.1]
 [877.2]
 [877.3]
 [877.4]] 877.5
[[877.2]
 [877.3]


In [ ]:
rnn1 = tf.keras.layers.SimpleRNN(units=1, activation='tanh', return_sequences=True) #units : 레이어의 뉴런 수

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X,Y, epochs=5000, verbose=0)
print(model.predict(X))

313/313 [==============================] - 1s 2ms/step
[[-2.3849487e-01]
 [-1.2188721e-01]
 [-5.8593750e-03]
 ...
 [ 9.9202051e+02]
 [ 9.9208472e+02]
 [ 9.9214893e+02]]


In [ ]:
print(model.predict(np.array([[[101.1], [101.2], [101.3], [101.4]]])))
print(model.predict(np.array([[[110.5], [110.6], [110.7], [110.8]]])))

[[97.515526]]
[[97.86932]]
