In [1]:
def set_initial_state(rooms = 6):
  import numpy as np
  return np.random.randint(0, rooms)

In [11]:
import os
import pandas as pd
import numpy as np
import random
os.getcwd()

'/content'

In [12]:
rewards= np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1 ,-1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

In [13]:
q_matrix = np.zeros((6,6))


In [3]:
def get_action(current_state, reward_matrix): # 입력값 : 현재 상태, 보상 행렬
  import random
  valid_actions = [] # 빈 행렬 생성
  for action in enumerate(reward_matrix[current_state]): # 현재 상태에 해당하는 보상에서 행동마다
    if action[1] != -1: # 보상이 -1이 아니라면
      valid_actions += [action[0]] # 유효행동행렬에 행동을 추가함
  return random.choice(valid_actions)  # 유효행동 중 무작위로 반환함

In [4]:
def take_action(current_state, reward_matrix, gamma, verbose = False): # 입력값 : 현재 상태, 보상 행렬, 감마 # verbose = False : 상세 정보 출력 X
  action = get_action(current_state, reward_matrix) # 유효행동 중 하나 반환
  sa_reward = reward_matrix[current_state, action] # 현재 상태와 그에 해당하는 행동을 보상 행렬에 추가
  ns_reward = max(q_matrix[action, ]) # 다음 상태의 상태-행동 보상값
  q_current_state = sa_reward + (gamma * ns_reward) # 현재 보상값에 다음 보상값에 gamma를 곱함
  q_matrix[current_state, action] = q_current_state # 다음 행동-보상값 정의
  new_state = action # 다음의 행동 정의
  if verbose:
    print(q_matrix)
    print(f"Old state: {current_state} | New state: {new_state}\n\n")
    if new_state == 5: # 5에 도달한다면 종료
      print(f"Agent has reached it's goal!")
  return new_state



In [5]:
def initialize_episode(reward_matrix, initial_state, gamma, verbose = False):
  current_state = initial_state # 에이전트가 목표 상태가 될때까지 시뮬레이션
  while True:
    current_state = take_action(current_state, reward_matrix, gamma, verbose)
    if current_state == 5:
      break

In [6]:
def train_agent(iterations, reward_matrix, gamma, verbose = False):
  print("Training in progress..") # 지정된 수의 에피소드를 실행한 후 행렬을 정규화
  for episode in range(iterations):
    initial_state = set_initial_state()
    initialize_episode(reward_matrix, initial_state, gamma, verbose)
  print("Training complete!")
  return q_matrix

In [7]:
def normalize_matrix(q_matrix):
  normalized_q = q_matrix / max(q_matrix[q_matrix.nonzero()]) * 100
  return normalized_q.astype(int)

In [16]:
gamma = 0.1
initial_state = 2 # 2번방에서 시작
initial_action = get_action(initial_state, rewards)
initialize_episode(rewards, initial_state, gamma, True)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
Old state: 2 | New state: 3


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  10.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
Old state: 3 | New state: 1


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  10.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]]
Old state: 1 | New state: 5


Agent has reached it's goal!


In [18]:
gamma = 0.8
initial_state = set_initial_state()
initial_action = get_action(initial_state, rewards)

pd.DataFrame(train_agent(2000, rewards, gamma, False))

Training in progress..
Training complete!


0      1      2      3      4      5
0    0.0    0.0    0.0    0.0  400.0    0.0
1    0.0    0.0    0.0  320.0    0.0  500.0
2    0.0    0.0    0.0  320.0    0.0    0.0
3    0.0  400.0  256.0    0.0  400.0    0.0
4  320.0    0.0    0.0  320.0    0.0  500.0
5    0.0  400.0    0.0    0.0  400.0  500.0