In [5]:
def f() :
    a = 5
    b = 6
    c = 7
    return {'a' : a, 'b' : b, 'c' : c}

In [6]:
a,b,c = f()

In [7]:
f()

{'a': 5, 'b': 6, 'c': 7}

In [37]:
string = ['aLaknv!', 'akdjiDKdkf?', '?dkjSdk']

In [ ]:
# strings의 문자열을 첫문자를 제외한 문자를 소문자로 만들어라

In [27]:
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]', '', value )
        value = value.title()
        result.append(value)
    return result

In [17]:
import re

In [29]:
clean_strings(string)

['Alaknv', 'Akdjidkdkf', 'Dkjsdk']

In [30]:
def move_punc(value):
    return re.sub('[!#?]', '', value)

In [33]:
clean_ops = [str.strip, str.title, move_punc]

In [42]:
def clean_stirngs(string, ops):
    result = []
    for value in string:
        for func in clean_ops:
            value = func(value)
        result.append(value)
    return result

In [43]:
clean_stirngs(string, clean_ops)

['Alaknv', 'Akdjidkdkf', 'Dkjsdk']

In [45]:
equiv_anon = lambda x : x*2

In [48]:
equiv_anon(4)

8

In [49]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

In [50]:
strings.sort(key = lambda x : len(set(list(x))))

In [51]:
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [52]:
def add_numbers(x, y):
    return x + y

In [53]:
add_five = lambda y : add_numbers(5, y
                    )

In [55]:
add_five(50)

55

In [57]:
from functools import partial
add_five = partial(add_numbers, 5)

In [59]:
some_dict = {'a' : 1, 'b' : 2, 'c' : 3}

In [60]:
dict_iterater = iter(some_dict)

In [61]:
dict_iterater

In [62]:
def squa( n = 10):
    print('generating squa from 1 to {0}'.format(n**2))
    for i in range(1, n + 1):
        yield i ** 2

In [64]:
gen = squa()

In [65]:
gen

<generator object squa at 0x000001E84DEDD200>

In [66]:
for x in gen:
    print(x , end = ' ')

generating squa from 1 to 100
1 4 9 16 25 36 49 64 81 100 

In [67]:
gen = (x ** 2 for x in range(100))

In [68]:
gen

<generator object <genexpr> at 0x000001E84DEDD580>

In [69]:
square()

NameError: name 'square' is not defined

In [79]:
def number_generator():
    yield 1
    yield 2
    yield 3

In [77]:
number_generator()

<generator object number_generator at 0x000001E84DEE8040>

In [72]:
g = number_generator()

In [74]:
g.__next__()

2

In [75]:
g.__next__()

3

In [84]:
for i in number_generator():
        print(i)

1
2
3


In [85]:
import itertools

In [86]:
first_letter = lambda x : x[0]

In [88]:
names = ['alan', 'adam' , 'wes', 'will', 'albert', 'steven']

In [92]:
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

a ['alan', 'adam']
w ['wes', 'will']
a ['albert']
s ['steven']


In [105]:
path = 'C:/Users/KO/Documents/qq.txt'

In [119]:
f = open(path, 'r')

In [107]:
f.close()

In [111]:
f = open('C:/Users/KO/Documents/tt.txt', 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

In [116]:
line = f.readline()

In [117]:
print(line)

dfg



In [120]:
while True:
    line = f.readline()
    if not line :
        break
    print(line)
f.close()

dfgdf

dfgsdfg

dfg

dsfgdg


In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10) : my_arr2 = my_arr * 2

Wall time: 19.9 ms


In [6]:
%time for _ in range(10) : my_list2 = [x * 2 for x in my_list]


Wall time: 857 ms


In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 0.01971585,  0.38004109,  0.28332439],
       [ 0.10565309, -1.00016761, -1.0765312 ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
# 같은 길이를 가지고 있는 리스트는 다차원 배열로 변환가능

In [16]:
data = [(1, 2, 3, 4), (5, 6, 7, 8)]

In [17]:
arr2 = np.array(data)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.array([1, 2, 3, 4, 5])

In [26]:
arr.dtype

dtype('int32')

In [27]:
float_arr = arr.astype(np.float64)

In [28]:
float_arr.dtype

dtype('float64')

In [29]:
arr = np.array([1,2.3, 3.4, 4.5])

In [30]:
int_arr = arr.astype(np.int32)

In [31]:
int_arr

array([1, 2, 3, 4])

In [35]:
arr = np.array([[1. , 2. , 3. ], [4. ,5., 6 ]])

In [37]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
names = np.array(['bob' ,'joe', 'will', 'bob', 'will', 'joe', 'joe'])

In [39]:
data = np.random.randn(7,4)

In [40]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [41]:
data

array([[-0.06789253, -0.33487792,  0.59936283,  1.22851813],
       [-1.09707089, -0.47491419,  0.14932562,  0.22076909],
       [-0.06045231,  0.75116666,  0.04223738,  1.90603084],
       [-0.03013089, -0.18276972,  0.742283  ,  1.945172  ],
       [ 1.23026183, -1.14458577, -0.15275491,  0.01935548],
       [-0.04978281,  0.20836286,  1.45510395, -1.14955795],
       [ 0.47897196,  0.23778392,  0.66894327, -0.72766061]])

In [44]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [46]:
data[names == 'bob', 2:]

array([[0.59936283, 1.22851813],
       [0.742283  , 1.945172  ]])

In [47]:
arr = np.empty((8,4))

In [48]:
arr

array([[1.21655878e-311, 1.03259720e-321, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 8.23907265e-067,
        2.73885895e-057],
       [1.46582663e-075, 1.42697677e-071, 6.81451388e-067,
        2.16385130e+190],
       [1.94918964e-153, 5.30581644e+180, 4.32453723e-096,
        2.14027814e+161],
       [1.47762371e+248, 4.30625279e-096, 4.82337723e+228,
        1.53259891e-047],
       [9.72163476e-072, 3.79228090e+179, 4.31394783e-033,
        4.26140842e-096],
       [1.16097020e-028, 1.26071127e-076, 2.42196513e-028,
        9.15781210e-072],
       [1.04917183e-153, 9.08366791e+223, 6.14415221e-144,
        4.05174788e-317]])

In [49]:
for i in range(8):
    arr[i] = i

In [50]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [51]:
arr[[[-3, -5, -7]]]

C:\Users\KO\AppData\Local\Temp/ipykernel_2384/3740665160.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  arr[[[-3, -5, -7]]]


array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [52]:
arr = np.arange(15).reshape((3,5))

In [53]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [56]:
arr = np.random.randn(6, 3)

In [57]:
arr

array([[-0.48062864,  1.02718723,  0.62104759],
       [-1.08591575, -0.79720897, -0.87024299],
       [ 0.97428085,  0.3815597 , -0.59290785],
       [ 0.16558598,  0.19203638,  0.13501006],
       [ 0.94154051,  0.70828242, -2.43721836],
       [-0.67140079,  1.21005477,  1.13441093]])

In [58]:
np.dot(arr.T, arr)

array([[ 3.72413634,  0.62999588, -2.96516989],
       [ 0.62999588,  3.83901804,  0.77785521],
       [-2.96516989,  0.77785521,  8.73971189]])

In [59]:
arr = np.arange(16).reshape((2,2,4))

In [60]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
arr.transpose((1, 0 ,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [62]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [63]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr = np.arange(10)

In [65]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
x = np.random.randn(8)
y = np.random.randn(8)

In [67]:
np.maximum(x, y)

array([ 0.8653142 ,  0.65797326,  1.13444686, -0.36021283,  0.13069129,
        0.14019269, -0.0603222 ,  0.40302088])

In [68]:
points = np.arange(-5, 5, 0.01)

In [69]:
xs, ys = np.meshgrid(points, points)

In [70]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [71]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [72]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [73]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [74]:
import matplotlib.pyplot as plt

In [75]:
xarr = np.array([1.1 ,1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [76]:
result = [(x if c else y)
         for x, y, z in zip(xarr, yarr, cond)]

NameError: name 'c' is not defined